### ISSUE TITLE
Nextcloud log flooded with error message

### ISSUE THREAD

**Issue by lhurt** [nextcloud/fulltextsearch_elasticsearch#28]
Hi,
i'm on 0.72 and see lots of the following entries in my nextcloud log
`sizeof(): Parameter must be an array or an object that implements Countable at /var/www/nextcloud.production/apps/fulltextsearch_elasticsearch/lib/Service/SearchMappingService.php#216`
any idea?

Thanks

**Comment by daita** [comment]
oups, should be fixed next release

**Comment by lhurt** [comment]
Thanks

**Comment by Wizlonex** [comment]
Hi:

I am finding very similar log entries on my Nextcloud 15.0.0 installation, which is highly related to the OnlyOffice app:

[PHP] Error: count(): Parameter must be an array or an object that implements Countable at /var/www/html/apps/onlyoffice/lib/appconfig.php#477

GET /index.php/apps/files/?fileNotFound=1
from 192.168.1.21 by username at 2018-12-26T13:39:21+00:00

My log is filling with these entries.  And I don't have to be using the OnlyOffice app for this to appear.  If I remove the app from the store, the log entries stop (but of course I lose my document server).  I also see this from time to time too:

[PHP] Error: Undefined offset: 2 at /var/www/html/apps/onlyoffice/controller/editorcontroller.php#434

GET /index.php/apps/onlyoffice/ajax/config/309564
from 192.168.1.21 by username at 2018-12-26T10:44:07+00:00

I am not sure if this is a Nextcloud problem or an Only Office problem (or maybe a bit of both), but since I found this (closed) thread I thought I would post here.

The document server still works with no apparent issues.

Installation:

Ubuntu 16.04 (installed in an LXC container)
PHP 7.2
Nextcloud 15.0.0
Apache2 - 2.4.37
